In [1]:
import numpy as np

In [2]:
matriz = np.array([
    [1, 0, 0],
    [-1/2, 0, 1/2],
    [1/2, 1, -3/2]
])

matriz_inversa = np.linalg.inv(matriz)

print(np.dot(matriz_inversa, matriz))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
